config/routes.rb
Rails.application.routes.draw do
  
  root "jobs#index"
  resources :jobs
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
	belongs_to :user

	# see http://www.rubydoc.info/gems/elasticsearch-model/Elasticsearch/Model/Callbacks
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

	validates :title, presence: true
	validates :company, presence: true
	validates :description, presence: true, length: { minimum: 10 }
	validates :url, presence: true
	validates :category_id, presence: true
	validates :location, presence: true

end

app/models/user.rb
require 'elasticsearch/model'

class User < ActiveRecord::Base
	has_secure_password
	has_many :jobs

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
	validates	:password, length: {minimum: 6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

  def index
    # if an Indeed search performed show search result in job index view
    if params[:q]. present? 
      @search = true
      # see indeed API gem documentation https://github.com/seejohnrun/indeed_api
      # search result which is @jobs is an Array
      # will pagination won't work with Array unless we tell Rails to require it
      # see file config/initializers/will_paginate_array_also.rb
      job_type = params[:jt].sub(/\s/, "") #remove space for full time and part time 
      @jobs = IndeedAPI.search_jobs(q: params[:q], l: params[:l], jt: job_type, limit: 25).results.paginate(page: params[:page], per_page: 5)
      puts job_type
    else # if no Indeed search performed show users posted jobs
      # if user don't click on filter link
    	if params[:category].blank?
        if params[:query].present? # if a bulletin search performed
          @bulletin_search = true
          # search results as records 
          # https://www.elastic.co/guide/en/elasticsearch/client/ruby-api/current/_activemodel_activerecord.html
    		  @jobs = Job.search(params[:query]).records.paginate(page: params[:page], per_page: 5)
        else
          @jobs = Job.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
        end
    	else 
        # when user click on filter link
        # find category chosen then get the category_id
    		@category_id = Category.find_by(name: params[:category]).id
        # filter the job base on categery_id
    		@jobs = Job.where(category_id: @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 5)
    	end
    end

  end

  def show
  end

  def new
    #don't let non logged in user see new job form
    if current_user
      @job = Job.new
    else
      flash[:error] = "Please signup or login to post a job."
      redirect_to login_path
    end
  end

  def create
    #prevent non logged in user to create new job
    if current_user
    	@job = current_user.jobs.new(job_params)
    	if @job.save
        flash[:notice] = "New job is sucessfully posted."
    		redirect_to job_path(@job)
    	else
        flash[:error] = @job.errors.full_messages.join(', ')
        #if validation failed, still keep the filled out contents
    		render action: :new
    	end
    else
      redirect_to login_path
    end
  end

  def edit
    #prevent non logged in user to see edit job form
    unless current_user == @job.user
      flash[:error] = "You can't edit other user's posted job."
      redirect_to job_path(@job)
    end
  end

  def update
    #prevent non logged in user to edit job
    if current_user == @job.user
    	if @job.update_attributes(job_params)
        flash[:notice] = "Sucessfully edited job."
    		redirect_to job_path(@job)
    	else
        flash[:error] = @job.errors.full_messages.join(', ')
    		redirect_to edit_job_path
    	end
    else
      redirect_to job_path(@job)
    end
  end

  def destroy
    if current_user == @job.user
    	@job.destroy
      flash[:notice] = "Sucessfully deleted your posted job."
    	redirect_to jobs_path
    else
      redirect_to job_path(@job)
    end
  end

private
	
	def job_params
		params.require(:job).permit(:title, :company, :description, :url, :category_id, :location)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		#prevent current user to see login page again
		@singup_login_page = true
		if current_user
			redirect_to user_path(current_user)
		end
	end

	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash[:error] = "Incorrect email or password."
			redirect_to login_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Successfully logged out."
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, except: [:index, :new, :create]
	before_action :authorize, except: [:show, :new, :create]

	def index
		@users = User.all
	end

	def new
		#don't let current user see signup page
		@singup_login_page = true
		if current_user
			redirect_to user_path(current_user)
		else
			@user = User.new
		end
	end

	def create
		#don't let current user create new account
		if current_user
			redirect_to user_path(current_user) 
		else 
			@user = User.new(user_params)
			if @user.save
				session[:user_id] = @user.id
				flash[:notice] = "Successfully signed up."
				redirect_to user_path(@user)
			else
				flash[:error] = @user.errors.full_messages.join(', ')
				redirect_to signup_path
			end
		end
	end

	def show
		#see private method
	end

	def edit
		#don't let current user see edit form of other user profile
		#see private method
		unless current_user == @user
			redirect_to user_path(current_user)
		end
	end

	def update
		#only current user can update his own account
		if current_user == @user
			if @user.update_attributes(user_params)
				flash[:notice] = "Successfully updated profile."
				redirect_to user_path(@user)
			else
				flash[:error] = @user.errors.full_messages.join(', ')
				redirect_to edit_user_path(@user)
			end
		else 
			#if someone else redirect to current user profile
			redirect_to user_path(current_user)
		end
	end

	def destroy
		#only current user can delete his own account
		if current_user == @user
			@user.destroy
			session[:user_id] = nil
			flash[:notice] = "Successfully delete profile."
			redirect_to root_path
		else
			redirect_to user_path(current_user)
		end
	end

private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def find_user
		@user = User.find_by_id(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<div class="containter">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<%= form_for @job do |f| %>
				<div class="form-group">
					<%= f.label :title  %>
					<%= f.text_field :title, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.label :category_id  %>
					<!-- see f.collection_select http://guides.rubyonrails.org/form_helpers.html -->
					<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"}, class: "form-control dropdown-toggle", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.label :company  %>
					<%= f.text_field :company, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.label :location  %>
					<%= f.text_field :location, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.label :description  %>
					<%= f.text_area :description, class: "form-control", rows: "4", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.label :url  %>
					<%= f.text_field :url, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.submit "Post", class: "btn btn-primary job_form_button" %>
					<%= link_to "Cancel", jobs_path, class: "btn btn-default job_form_button" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<%= render "form" %>

app/views/jobs/index.html.erb
<!-- Indeed Search Engine -->
<div class="indeed_search text-center", id="index_header">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<%= form_tag(root_path, method: :get, class: "form-inline text-center", id: "indeed_search") do %>
				<h2>LOOKING FOR A JOB?</h2>
				<div class="form-group">
					<%= text_field_tag :q, nil, class: "form-control", placeholder: "Job Title or Keywords", autofocus: true, required: true %>
				</div>
				<div class="form-group">
					<%= text_field_tag :l, nil, class: "form-control", placeholder: "City, State or Zipcode", autofocus: true %>
				</div>
				<div class="form-group">
					<%= select_tag :jt, options_for_select([ "Full Time", "Part Time", "Contract", "Temporary", "Internship", "Commission" ], "Full Time"), class: "form-control" %>
				</div>
				<div class="form-group">
					<%= submit_tag "Indeed Search", class: "btn btn-primary" %>
				</div>
				<p>jobs by <span><img src="http://img.informer.com/icons/png/48/3798/3798889.png" style="height: 20px"></span></p>
			<% end %>
		</div>
	</div>
</div>

<!-- Heading -->
<div class="text-center" id="index_heading">
	<% if !@category_id and !@search%> 
		<!-- show "Job Bulletin" as title in as default or if All Job clicked -->
		<h1>Job Bulletin</h1>
	<% elsif @category_id and !@search  %>
		<!-- show category job as title if user click on category -->
		<h1><%=  Category.find(@category_id).name %> Jobs</h1>
	<% elsif @search %>
		<!-- if an indeed search performed "Indeed Search Results" is the title -->
		<h1>Indeed Search Results</h1>
	<% end %>
</div>

<!-- jobs and search result -->
<div class="col-lg-10 col-lg-offset-1">
	<% if @search %>
		<!-- if an Indeed search performed, show search result -->
		<% if @jobs.any? %>
			<% @jobs.each do |job| %>
				<h3><%= link_to job.job_title, job.url %></h3>
				<h5><strong>Company: </strong><%= job.company %> - <%=  job.formatted_location_full %></h5>
				<h5>Posted: <%= time_ago_in_words(job.date) %> ago.</h5>
				<h5><strong>Description Snippet: </strong><%= job.snippet %>... <%= link_to "learn more", job.url , class: "learn_more" %>.</h5>
				<hr>
			<% end %>
		<% else %>
			<!-- alert message when no jobs found in Indeed -->
			<div class="alert alert-warning">
				<h4 class="text-center">The search <strong><i><%= params[:q]%> <%= params[:l].strip.empty? ? '' : 'in ' + params[:l] + ' ' %></i></strong>does not match any jobs</h4>
			</div>
		<% end  %>
	<% else %>
		
		<!-- when no search performed show user posted jobs -->
		<% if @jobs.any? %>
			<!-- if there are any job posted belong to this catetory, list them -->
			<% @jobs.each do |job| %>
			  <h3><%= link_to job.title, job_path(job), class: "index_job_title" %></h3>
			  <p><i><%= job.category.name %> - Posted by: <%= link_to User.find(job.user_id).first_name, user_path(User.find(job.user_id)), class: "post_user_name" %> (<%= time_ago_in_words(job.created_at) %> ago)</i></p>
				<h5><strong>Company: </strong><%= job.company %> - <%= job.location %></h5>
				<!-- only print first 10 words of the job description -->
				<h5><strong>Description Snippet: </strong><%= job.description.split(" ").slice(0,10).join(" ") %>... <%= link_to "learn more", job_path(job), class: "learn_more" %>.</h5>
				<hr>
			<% end %>
			<% else %>
				<div class="text-center">
					<% if @bulletin_search %>
						<!-- when no result found for a bulletin search -->
						<h2>No jobs in the Bulletin match keyword "<%= params[:query] %>"</h2>
						<%= link_to "Back to Bulletin", jobs_path %>
					<% else %>
						<!-- show this message if no jost posted in this category  -->
						<h2>There aren't any jobs posted yet!</h2>
					<% end %>
				</div>
			<% end %>

	<% end %>

	<div class="pagination_holder text-center">
		<%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>
<%= render "form" %>

app/views/jobs/show.html.erb
<div class="col-lg-10 col-lg-offset-1">
	<h2><%= @job.title %></h2>
	<p><i><%= @job.category.name %></i></p>
	<h4>Company: <%= @job.company %></h4>
	<p>Job Description: <%= simple_format @job.description %></p>
	<%= link_to "Apply for Job", @job.url, class: "btn btn-primary" %>
	<hr>
	<%= link_to "Job Bulletin", jobs_path, class: "btn btn-default three-button-group" %>

	<% if current_user == @job.user %>
		<!-- only show edit and delete if the post belongs to current user -->
		<%= link_to "Edit", edit_job_path(@job), class: "btn btn-default three-button-group" %>
		<%= link_to "Delete", @job, method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-default three-button-group" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dev Job Bulletin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @singup_login_page ? 'singup_login_page' : ''%>">
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "DevJobs", jobs_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Jobs Category <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Jobs", jobs_path %></li>
              <% Category.all.each do |category| %>
                <!-- loop to each category -->
                <!-- sample url http://localhost:3000/jobs?category=Full+Time -->
                <li><%= link_to category.name, jobs_path(category: category.name) %></li>
              <% end  %>
            </ul>
          </li>
        </ul>
    
        <div class="col-sm-3 col-md-3">
          <%= form_tag jobs_path, method: :get, class: "navbar-form", role: "search" do %>
            <div class="input-group">
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search Bulletin", autofocus: true %>
              <div class="input-group-btn">
                <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                  <span class="glyphicon glyphicon-search"></span> 
                <% end %>
              </div>
            </div>
          <% end %>
      </div>

        <ul class="nav navbar-nav navbar-right">
          <li><%=  link_to "Add Job", new_job_path %></li>
          <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
      </div>
    </div>
  </nav>
  <!-- error message -->
  <% flash.each do |name, msg| %>
    <div class="alert <%= name == 'error' ? 'alert-danger' : 'alert-info' %>">
      <div class="container">
        <%= msg %>
      </div>
    </div>
  <% end %>

	<div class="container-fluid">
		<div class="row">
			<!-- <div class="col-md-10 col-md-offset-1"> -->
				<%= yield %>
			<!-- </div> -->
		</div>
	</div>

</body>
</html>

app/views/users/edit.html.erb
<div class="containter">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<h1>Edit Profile</h1>
			<hr>
			<%=  form_for @user do |f| %>
				<div class="form-group">
					<%=  f.label :first_name %>
					<%=  f.text_field :first_name, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%=  f.label :last_name %>
					<%=  f.text_field :last_name, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%=  f.label :email %>
					<%=  f.email_field :email, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.submit "Edit", class: "btn btn-primary" %>
					<%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="containter">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3 user_signup_form">
			<%= form_for @user do |f| %>
				<div id="slogan" class="text-center">
					<h3>Looking for a Job?</h3>
					<h4>Join DevJob Community to find or share jobs.</h4>
				</div>
				<div class="form-group">
					<%=  f.label :first_name %>
					<%=  f.text_field :first_name, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%=  f.label :last_name %>
					<%=  f.text_field :last_name, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%=  f.label :email %>
					<%=  f.email_field :email, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%=  f.label :password %>
					<%=  f.password_field :password, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%=  f.label :password_confirmation %>
					<%=  f.password_field :password_confirmation, class: "form-control", autofocus: true %>
				</div>
				<div class="form-group">
					<%= f.submit "Sign Up", class: "btn btn-primary form-control signup_button" %>
				</div>
			<% end %>
			<p class="text-center">Already have an account? <%= link_to "Click Here", login_path %> to log in.</p>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
	<!-- show "Hello, " with user first name if current user see his own profile -->
	<h2>Hello, <%= @user.first_name.titleize %></h2>
<% else %>
	<!-- do not show "Hello, " when current user look at other user's profile -->
	<h2><%= @user.first_name.titleize %> <%= @user.last_name.titleize %></h2>
<% end %>
<h4><strong>Email: </strong><%= mail_to @user.email, nil, class: "mail_to" %></h4>
<hr>
<%= link_to "Home", jobs_path, class: "btn btn-default" %>

<% if current_user == @user %> 
	<!-- only show Edit and Delete button in current user profile -->
	<%=  link_to "Edit Profile", edit_user_path(@user), class: "btn btn-default" %>
	<%=  link_to "Delete Profile", @user, method: :delete, class: "btn btn-default" %>
<% end %>

<% if @user.jobs.any? %>
	<!-- show user posted jobs -->
	<h2>Posted Jobs</h2>
	<% @user.jobs.each do |job| %>
		  <h3><%= link_to job.title, job_path(job), class: "index_job_title" %></h3>
		  <p><i><%= job.category.name %> - Posted by: <%= link_to User.find(job.user_id).first_name, user_path(User.find(job.user_id)), class: "post_user_name" %> (<%= time_ago_in_words(job.created_at) %> ago)</i></p>
			<h5><strong>Company: </strong><%= job.company %> - <%= job.location %></h5>
			<!-- only print first 10 words of the job description -->
			<h5><strong>Description Snippet: </strong><%= job.description.split(" ").slice(0,10).join(" ") %>... <%= link_to "learn more", job_path(job), class: "learn_more" %>.</h5>
			<% if current_user == @user %>
			<!-- only show edit and delete button for current user -->
				<%= link_to "Edit", edit_job_path(job), class: "btn btn-default three-button-group" %>
				<%= link_to "Delete", job, method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-default three-button-group" %>
			<% end %>
			<hr>
		<% end %>
<% elsif @user.jobs.empty? and current_user == @user %>
<!-- if current user use the word "You" -->
	<h3>You haven't posted any jobs yet.</h3>
	<%= link_to "Add Job", new_job_path, class: "btn btn-default" %>
<% elsif @user.jobs.empty? and current_user != @user %>
<!-- if not current user use "This user" -->
	<h3>This user hasn't posted any jobs yet.</h3>
<% end %>